name: Create Release and Package Artifacts
on: workflow_dispatch

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: "[TODO]"
          draft: true
          prerelease: false
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: buid project
        run: ./gradlew shipJar
      - name: zip release
        run: zip ./build/AntiProcrastinationThingy.zip ./build/libs/**/*
      - name: upload zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./build/AntiProcrastinationThingy.zip
          asset_name: AntiProcrastinationThingy.zip
          asset_content_type: application/zip
